import { useState, useEffect } from 'react';
import { MonthlyRentalInvoiceList } from './MonthlyRentalInvoiceList';
import { MonthlyRentalInvoiceDetails } from './MonthlyRentalInvoiceDetails';
import { MonthlyRentalInvoice, RentalContract, BillingCycleLog, MonthlyRentalItem } from '../../types/monthly-rental';
import { toast } from 'sonner';
import { uploadPaymentProof } from '@/lib/upload';

type View = 'list' | 'details';

// Sample rental items
const sampleRentalItems: MonthlyRentalItem[] = [
  {
    id: 'item-1',
    scaffoldingItemId: 'std-frame-1',
    itemName: 'Standard Frame 1.8m x 1.2m',
    quantity: 50,
    unitPrice: 15.00,
    rentalDuration: '30 days',
    monthlyRate: 450.00,
    totalPrice: 22500.00,
  },
  {
    id: 'item-2',
    scaffoldingItemId: 'cross-brace-1',
    itemName: 'Cross Brace 1.8m',
    quantity: 100,
    unitPrice: 8.00,
    rentalDuration: '30 days',
    monthlyRate: 240.00,
    totalPrice: 24000.00,
  },
  {
    id: 'item-3',
    scaffoldingItemId: 'base-jack-1',
    itemName: 'Base Jack (Adjustable)',
    quantity: 60,
    unitPrice: 12.00,
    rentalDuration: '30 days',
    monthlyRate: 360.00,
    totalPrice: 21600.00,
  },
];

const initialContracts: RentalContract[] = [
  {
    id: 'contract-1',
    agreementId: 'AGR-2024-001',
    deliveryOrderNumber: 'DO-2024-001',
    customerId: 'CUST-001',
    customerName: 'Acme Construction Ltd.',
    customerAddress: '123 Construction Ave, Johor Bahru, Johor 81200',
    customerContact: '+60 12-345 6789',
    contractStartDate: '2024-10-01T00:00:00Z',
    billingCycleDay: 1, // Bill on 1st of each month
    rentalItems: sampleRentalItems,
    isActive: true,
    itemsReturned: false,
    doSignedAt: '2024-10-01T10:00:00Z',
    createdAt: '2024-10-01T09:00:00Z',
    lastUpdated: '2024-10-01T09:00:00Z',
  },
  {
    id: 'contract-2',
    agreementId: 'AGR-2024-002',
    deliveryOrderNumber: 'DO-2024-002',
    customerId: 'CUST-002',
    customerName: 'BuildRight Inc.',
    customerAddress: '456 Builder Street, Kuala Lumpur 50000',
    customerContact: '+60 13-456 7890',
    contractStartDate: '2024-11-15T00:00:00Z',
    billingCycleDay: 15, // Bill on 15th of each month
    rentalItems: [
      {
        id: 'item-4',
        scaffoldingItemId: 'plank-1',
        itemName: 'Steel Plank 2.0m',
        quantity: 80,
        unitPrice: 20.00,
        rentalDuration: '30 days',
        monthlyRate: 600.00,
        totalPrice: 48000.00,
      },
    ],
    isActive: true,
    itemsReturned: false,
    doSignedAt: '2024-11-15T14:00:00Z',
    createdAt: '2024-11-15T13:00:00Z',
    lastUpdated: '2024-11-15T13:00:00Z',
  },
];

const initialInvoices: MonthlyRentalInvoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-MR-2024-10-0001',
    deliveryOrderNumber: 'DO-2024-001',
    agreementId: 'AGR-2024-001',
    customerId: 'CUST-001',
    customerName: 'Acme Construction Ltd.',
    customerAddress: '123 Construction Ave, Johor Bahru, Johor 81200',
    customerContact: '+60 12-345 6789',
    billingMonth: 1,
    billingPeriodStart: '2024-10-01T00:00:00Z',
    billingPeriodEnd: '2024-10-31T23:59:59Z',
    rentalItems: sampleRentalItems,
    subtotal: 68100.00,
    taxRate: 0,
    taxAmount: 0,
    grandTotal: 68100.00,
    defaultInterestRate: 0.015, // 1.5% per month
    status: 'Paid',
    dueDate: '2024-10-08T00:00:00Z',
    createdAt: '2024-10-01T10:00:00Z',
    lastUpdated: '2024-10-05T15:00:00Z',
    isAutoGenerated: true,
    autoGeneratedAt: '2024-10-01T10:00:00Z',
    itemsReturned: false,
    notes: 'First month invoice - automatically generated upon delivery order confirmation.',
    paymentProof: {
      id: 'proof-1',
      fileName: 'payment_oct_2024.pdf',
      fileUrl: '#',
      fileSize: 245000,
      fileType: 'application/pdf',
      uploadedAt: '2024-10-03T09:00:00Z',
    },
    paymentSubmittedAt: '2024-10-03T09:00:00Z',
    transactionReferenceId: 'TXN-20241003-001234',
    approvedBy: 'Finance Manager',
    approvedAt: '2024-10-05T15:00:00Z',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-MR-2024-11-0002',
    deliveryOrderNumber: 'DO-2024-001',
    agreementId: 'AGR-2024-001',
    customerId: 'CUST-001',
    customerName: 'Acme Construction Ltd.',
    customerAddress: '123 Construction Ave, Johor Bahru, Johor 81200',
    customerContact: '+60 12-345 6789',
    billingMonth: 2,
    billingPeriodStart: '2024-11-01T00:00:00Z',
    billingPeriodEnd: '2024-11-30T23:59:59Z',
    rentalItems: sampleRentalItems,
    subtotal: 68100.00,
    taxRate: 0,
    taxAmount: 0,
    grandTotal: 68100.00,
    defaultInterestRate: 0.015, // 1.5% per month
    status: 'Pending Approval',
    dueDate: '2024-11-08T00:00:00Z',
    createdAt: '2024-11-01T00:00:00Z',
    lastUpdated: '2024-11-25T10:00:00Z',
    isAutoGenerated: true,
    autoGeneratedAt: '2024-11-01T00:00:00Z',
    itemsReturned: false,
    notes: 'Month 2 invoice - automatically generated as rental continues. Items have not yet been returned.',
    paymentProof: {
      id: 'proof-2',
      fileName: 'payment_nov_2024.jpg',
      fileUrl: '#',
      fileSize: 189000,
      fileType: 'image/jpeg',
      uploadedAt: '2024-11-25T10:00:00Z',
    },
    paymentSubmittedAt: '2024-11-25T10:00:00Z',
  },
  {
    id: 'inv-3',
    invoiceNumber: 'INV-MR-2024-11-0003',
    deliveryOrderNumber: 'DO-2024-002',
    agreementId: 'AGR-2024-002',
    customerId: 'CUST-002',
    customerName: 'BuildRight Inc.',
    customerAddress: '456 Builder Street, Kuala Lumpur 50000',
    customerContact: '+60 13-456 7890',
    billingMonth: 1,
    billingPeriodStart: '2024-11-15T00:00:00Z',
    billingPeriodEnd: '2024-12-14T23:59:59Z',
    rentalItems: [
      {
        id: 'item-4',
        scaffoldingItemId: 'plank-1',
        itemName: 'Steel Plank 2.0m',
        quantity: 80,
        unitPrice: 20.00,
        rentalDuration: '30 days',
        monthlyRate: 600.00,
        totalPrice: 48000.00,
      },
    ],
    subtotal: 48000.00,
    taxRate: 0,
    taxAmount: 0,
    grandTotal: 48000.00,
    defaultInterestRate: 0.015, // 1.5% per month
    status: 'Pending Payment',
    dueDate: '2024-11-22T00:00:00Z',
    createdAt: '2024-11-15T14:00:00Z',
    lastUpdated: '2024-11-15T14:00:00Z',
    isAutoGenerated: true,
    autoGeneratedAt: '2024-11-15T14:00:00Z',
    itemsReturned: false,
    notes: 'First month invoice - automatically generated upon delivery order confirmation.',
  },
  {
    id: 'inv-4',
    invoiceNumber: 'INV-MR-2024-12-0004',
    deliveryOrderNumber: 'DO-2024-001',
    agreementId: 'AGR-2024-001',
    customerId: 'CUST-001',
    customerName: 'Acme Construction Ltd.',
    customerAddress: '123 Construction Ave, Johor Bahru, Johor 81200',
    customerContact: '+60 12-345 6789',
    billingMonth: 3,
    billingPeriodStart: '2024-12-01T00:00:00Z',
    billingPeriodEnd: '2024-12-31T23:59:59Z',
    rentalItems: sampleRentalItems,
    subtotal: 68100.00,
    taxRate: 0,
    taxAmount: 0,
    grandTotal: 68100.00,
    defaultInterestRate: 0.015, // 1.5% per month
    status: 'Rejected',
    dueDate: '2024-12-15T00:00:00Z',
    createdAt: '2024-12-01T00:00:00Z',
    lastUpdated: '2024-12-08T14:30:00Z',
    isAutoGenerated: true,
    autoGeneratedAt: '2024-12-01T00:00:00Z',
    itemsReturned: false,
    notes: 'Month 3 invoice - automatically generated as rental continues. Items have not yet been returned.',
    rejectedBy: 'Finance Manager',
    rejectedAt: '2024-12-08T14:30:00Z',
    rejectionReason: 'Payment proof image is unclear. Please upload a clearer screenshot showing transaction details and amount.',
  },
  {
    id: 'inv-5',
    invoiceNumber: 'INV-MR-2025-12-0005',
    deliveryOrderNumber: 'DO-2024-002',
    agreementId: 'AGR-2024-002',
    customerId: 'CUST-002',
    customerName: 'BuildRight Inc.',
    customerAddress: '456 Builder Street, Kuala Lumpur 50000',
    customerContact: '+60 13-456 7890',
    billingMonth: 2,
    billingPeriodStart: '2025-12-01T00:00:00Z',
    billingPeriodEnd: '2025-12-31T23:59:59Z',
    rentalItems: [
      {
        id: 'item-5',
        scaffoldingItemId: 'plank-1',
        itemName: 'Steel Plank 2.0m',
        quantity: 80,
        unitPrice: 20.00,
        rentalDuration: '30 days',
        monthlyRate: 600.00,
        totalPrice: 48000.00,
      },
    ],
    subtotal: 48000.00,
    taxRate: 0,
    taxAmount: 0,
    grandTotal: 48000.00,
    defaultInterestRate: 0.015, // 1.5% per month
    status: 'Pending Payment',
    dueDate: '2025-12-31T00:00:00Z',
    createdAt: '2025-12-01T00:00:00Z',
    lastUpdated: '2025-12-01T00:00:00Z',
    isAutoGenerated: true,
    autoGeneratedAt: '2025-12-01T00:00:00Z',
    itemsReturned: false,
    notes: 'Month 2 invoice - automatically generated as rental continues. Items have not yet been returned.',
  },
];

interface MonthlyRentalBillingProps {
  userRole?: 'Admin' | 'Finance' | 'Staff' | 'Customer';
}

export function MonthlyRentalBilling({ userRole = 'Admin' }: MonthlyRentalBillingProps) {
  const [currentView, setCurrentView] = useState<View>('list');
  const [invoices, setInvoices] = useState<MonthlyRentalInvoice[]>(initialInvoices);
  const [contracts, setContracts] = useState<RentalContract[]>(initialContracts);
  const [selectedInvoiceId, setSelectedInvoiceId] = useState<string | null>(null);
  const [billingLogs, setBillingLogs] = useState<BillingCycleLog[]>([]);

  // Load data from localStorage on mount
  useEffect(() => {
    const storedInvoices = localStorage.getItem('monthlyRentalInvoices');
    const storedContracts = localStorage.getItem('rentalContracts');
    const storedLogs = localStorage.getItem('billingCycleLogs');
    
    if (storedInvoices) {
      try {
        setInvoices(JSON.parse(storedInvoices));
      } catch (e) {
        console.error('Failed to load invoices');
      }
    }
    
    if (storedContracts) {
      try {
        setContracts(JSON.parse(storedContracts));
      } catch (e) {
        console.error('Failed to load contracts');
      }
    }
    
    if (storedLogs) {
      try {
        setBillingLogs(JSON.parse(storedLogs));
      } catch (e) {
        console.error('Failed to load billing logs');
      }
    }
  }, []);

  // Save to localStorage when data changes
  useEffect(() => {
    localStorage.setItem('monthlyRentalInvoices', JSON.stringify(invoices));
  }, [invoices]);

  useEffect(() => {
    localStorage.setItem('rentalContracts', JSON.stringify(contracts));
  }, [contracts]);

  useEffect(() => {
    localStorage.setItem('billingCycleLogs', JSON.stringify(billingLogs));
  }, [billingLogs]);

  // Auto-generate invoices for active contracts
  useEffect(() => {
    const checkAndGenerateInvoices = () => {
      const now = new Date();
      const today = now.getDate();
      
      contracts.forEach(contract => {
        if (!contract.isActive || contract.itemsReturned) {
          return; // Skip inactive or returned contracts
        }
        
        // Check if it's billing day
        if (today !== contract.billingCycleDay) {
          return;
        }
        
        // Calculate which billing month this should be
        const contractStart = new Date(contract.contractStartDate);
        const monthsDiff = (now.getFullYear() - contractStart.getFullYear()) * 12 
          + (now.getMonth() - contractStart.getMonth());
        const billingMonth = monthsDiff + 1;
        
        // Check if invoice for this month already exists
        const existingInvoice = invoices.find(
          inv => inv.agreementId === contract.agreementId && inv.billingMonth === billingMonth
        );
        
        if (existingInvoice) {
          return; // Invoice already generated
        }
        
        // Generate new invoice
        generateMonthlyInvoice(contract, billingMonth);
      });
    };
    
    // Check daily at midnight
    const checkInterval = setInterval(checkAndGenerateInvoices, 24 * 60 * 60 * 1000);
    
    // Also check immediately on mount
    checkAndGenerateInvoices();
    
    return () => clearInterval(checkInterval);
  }, [contracts, invoices]);

  // Check for overdue invoices
  useEffect(() => {
    const checkOverdue = () => {
      const now = new Date();
      now.setHours(0, 0, 0, 0);
      
      const updatedInvoices = invoices.map(invoice => {
        if (invoice.status === 'Pending Payment' && !invoice.paymentProof) {
          const dueDate = new Date(invoice.dueDate);
          dueDate.setHours(0, 0, 0, 0);
          
          if (dueDate < now) {
            return {
              ...invoice,
              status: 'Overdue' as const,
              lastUpdated: new Date().toISOString(),
            };
          }
        }
        return invoice;
      });
      
      const hasChanges = updatedInvoices.some((inv, i) => inv.status !== invoices[i].status);
      if (hasChanges) {
        setInvoices(updatedInvoices);
      }
    };
    
    checkOverdue();
    const interval = setInterval(checkOverdue, 60000);
    return () => clearInterval(interval);
  }, [invoices]);

  const generateMonthlyInvoice = (contract: RentalContract, billingMonth: number) => {
    const now = new Date();
    const invoiceNumber = `INV-MR-${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(Date.now()).slice(-4)}`;
    
    // Calculate billing period
    const periodStart = new Date(contract.contractStartDate);
    periodStart.setMonth(periodStart.getMonth() + (billingMonth - 1));
    const periodEnd = new Date(periodStart);
    periodEnd.setMonth(periodEnd.getMonth() + 1);
    periodEnd.setDate(periodEnd.getDate() - 1);
    
    // Calculate due date (e.g., 7 days from invoice date)
    const dueDate = new Date(now);
    dueDate.setDate(dueDate.getDate() + 7);
    
    // Calculate totals
    const subtotal = contract.rentalItems.reduce((sum, item) => sum + item.totalPrice, 0);
    const taxRate = 0; // No tax as per requirements
    const taxAmount = subtotal * taxRate;
    const grandTotal = subtotal + taxAmount;
    
    const newInvoice: MonthlyRentalInvoice = {
      id: `inv-${Date.now()}`,
      invoiceNumber,
      deliveryOrderNumber: contract.deliveryOrderNumber,
      agreementId: contract.agreementId,
      customerId: contract.customerId,
      customerName: contract.customerName,
      customerAddress: contract.customerAddress,
      customerContact: contract.customerContact,
      billingMonth,
      billingPeriodStart: periodStart.toISOString(),
      billingPeriodEnd: periodEnd.toISOString(),
      rentalItems: contract.rentalItems,
      subtotal,
      taxRate,
      taxAmount,
      grandTotal,
      defaultInterestRate: 0.015, // 1.5% per month
      status: 'Pending Payment',
      dueDate: dueDate.toISOString(),
      createdAt: now.toISOString(),
      lastUpdated: now.toISOString(),
      isAutoGenerated: true,
      autoGeneratedAt: now.toISOString(),
      itemsReturned: false,
      notes: billingMonth === 1
        ? 'First month invoice - automatically generated upon delivery order confirmation.'
        : `Month ${billingMonth} invoice - automatically generated as rental continues. Items have not yet been returned.`,
    };
    
    setInvoices(prev => [...prev, newInvoice]);
    
    // Log the generation
    const log: BillingCycleLog = {
      id: `log-${Date.now()}`,
      contractId: contract.id,
      cycleNumber: billingMonth,
      generatedAt: now.toISOString(),
      invoiceId: newInvoice.id,
      status: 'generated',
    };
    setBillingLogs(prev => [...prev, log]);
    
    toast.success(`Invoice ${invoiceNumber} generated for ${contract.customerName} - Month ${billingMonth}`);
  };

  const handleView = (id: string) => {
    setSelectedInvoiceId(id);
    setCurrentView('details');
  };

  const handleBack = () => {
    setCurrentView('list');
    setSelectedInvoiceId(null);
  };

  const handleSubmitPayment = async (invoiceId: string, file: File) => {
    const now = new Date().toISOString();
    
    // Upload file to server
    toast.info('Uploading payment proof...');
    const result = await uploadPaymentProof(file);
    
    if (!result.success || !result.url) {
      toast.error(result.error || 'Failed to upload payment proof');
      return;
    }
    
    const paymentProof = {
      id: `proof-${Date.now()}`,
      fileName: file.name,
      fileUrl: result.url, // Use server URL instead of blob URL
      fileSize: file.size,
      fileType: file.type,
      uploadedAt: now,
    };
    
    setInvoices(invoices.map(inv =>
      inv.id === invoiceId
        ? {
            ...inv,
            status: 'Pending Approval',
            paymentProof,
            paymentSubmittedAt: now,
            lastUpdated: now,
          }
        : inv
    ));
    
    toast.success('Payment proof submitted successfully');
    setCurrentView('list');
  };

  const handleEditPayment = (invoiceId: string) => {
    setSelectedInvoiceId(invoiceId);
    setCurrentView('details');
  };

  const handleApprove = (invoiceId: string, transactionReferenceId: string) => {
    const now = new Date().toISOString();
    
    setInvoices(invoices.map(inv =>
      inv.id === invoiceId
        ? {
            ...inv,
            status: 'Paid',
            transactionReferenceId,
            approvedBy: 'Current User (Admin)',
            approvedAt: now,
            lastUpdated: now,
          }
        : inv
    ));
    
    toast.success('Payment approved successfully');
    setCurrentView('list');
  };

  const handleReject = (invoiceId: string, reason: string) => {
    const now = new Date().toISOString();
    
    setInvoices(invoices.map(inv =>
      inv.id === invoiceId
        ? {
            ...inv,
            status: 'Rejected',
            rejectedBy: 'Current User (Admin)',
            rejectedAt: now,
            rejectionReason: reason,
            paymentProof: undefined, // Clear payment proof on rejection
            lastUpdated: now,
          }
        : inv
    ));
    
    toast.error('Payment rejected');
    setCurrentView('list');
  };

  const handleMarkAsReturned = (invoiceId: string) => {
    const invoice = invoices.find(inv => inv.id === invoiceId);
    if (!invoice) return;
    
    const now = new Date().toISOString();
    
    // Update the invoice - mark as completed
    setInvoices(invoices.map(inv =>
      inv.id === invoiceId
        ? {
            ...inv,
            status: 'Completed' as const,
            itemsReturned: true,
            returnedAt: now,
            lastUpdated: now,
          }
        : inv
    ));
    
    // Update the contract to stop future billing
    setContracts(contracts.map(contract =>
      contract.agreementId === invoice.agreementId
        ? {
            ...contract,
            itemsReturned: true,
            returnDate: now,
            isActive: false,
            lastUpdated: now,
          }
        : contract
    ));
    
    toast.success('Items marked as returned. No further invoices will be generated.');
  };

  const selectedInvoice = selectedInvoiceId
    ? invoices.find(inv => inv.id === selectedInvoiceId)
    : null;

  return (
    <div className="space-y-6">
      {currentView === 'list' && (
        <>
          <div className="space-y-2">
            <h1>Monthly Rental Billing</h1>
            <p className="text-[#374151]">
              Automated monthly rental invoicing with payment tracking and approval workflows
            </p>
          </div>
          
          <MonthlyRentalInvoiceList
            invoices={invoices}
            onView={handleView}
            onEditPayment={handleEditPayment}
            userRole={userRole}
          />
        </>
      )}
      
      {currentView === 'details' && selectedInvoice && (
        <MonthlyRentalInvoiceDetails
          invoice={selectedInvoice}
          onBack={handleBack}
          onSubmitPayment={handleSubmitPayment}
          onApprove={handleApprove}
          onReject={handleReject}
          onMarkAsReturned={handleMarkAsReturned}
          userRole={userRole}
        />
      )}
    </div>
  );
}