export interface MonthlyRentalInvoice {
  id: string;
  invoiceNumber: string;
  deliveryOrderNumber: string;
  agreementId: string;
  customerId: string;
  customerName: string;
  customerAddress: string;
  customerContact: string;
  
  // Billing cycle information
  billingMonth: number; // 1 for first month, 2 for second month, etc.
  billingPeriodStart: string;
  billingPeriodEnd: string;
  
  // Rental items
  rentalItems: MonthlyRentalItem[];
  
  // Financial information
  subtotal: number;
  taxRate: number;
  taxAmount: number;
  grandTotal: number;
  defaultInterestRate: number; // Monthly interest rate for overdue payments (e.g., 0.015 for 1.5%)
  
  // Status tracking
  status: 'Pending Payment' | 'Pending Approval' | 'Paid' | 'Rejected' | 'Overdue' | 'Completed';
  dueDate: string;
  createdAt: string;
  lastUpdated: string;
  
  // Payment tracking
  paymentProof?: InvoiceDocument;
  paymentSubmittedAt?: string;
  transactionReferenceId?: string; // Reference/Transaction ID entered during approval
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
  
  // Auto-generation tracking
  isAutoGenerated: boolean;
  autoGeneratedAt?: string;
  
  // Return tracking
  itemsReturned: boolean;
  returnedAt?: string;
  
  // Notes
  notes?: string;
}

export interface MonthlyRentalItem {
  id: string;
  scaffoldingItemId: string;
  itemName: string;
  quantity: number;
  unitPrice: number;
  rentalDuration: string; // e.g., "30 days", "1 month"
  monthlyRate: number;
  totalPrice: number;
}

export interface InvoiceDocument {
  id: string;
  fileName: string;
  fileUrl: string;
  fileSize: number;
  fileType: string;
  uploadedAt: string;
}

export interface RentalContract {
  id: string;
  agreementId: string;
  deliveryOrderNumber: string;
  customerId: string;
  customerName: string;
  customerAddress: string;
  customerContact: string;
  
  // Contract dates
  contractStartDate: string;
  contractEndDate?: string;
  billingCycleDay: number; // Day of month for billing (e.g., 1 for 1st of month)
  
  // Rental items
  rentalItems: MonthlyRentalItem[];
  
  // Status
  isActive: boolean;
  itemsReturned: boolean;
  returnDate?: string;
  
  // DO reference
  doSignedAt?: string;
  
  createdAt: string;
  lastUpdated: string;
}

export interface BillingCycleLog {
  id: string;
  contractId: string;
  cycleNumber: number;
  generatedAt: string;
  invoiceId?: string;
  status: 'generated' | 'skipped' | 'failed';
  reason?: string;
}